# Generated by Django 4.0.6 on 2022-09-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated',
        ),
    ]
