# Generated by Django 4.0.6 on 2022-09-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topsection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_title', models.CharField(blank=True, max_length=100, null=True)),
                ('topsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar_application.topsection')),
            ],
        ),
        migrations.CreateModel(
            name='Topsection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('topsection1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar_application.topsection1')),
            ],
        ),
    ]
