# Generated by Django 4.0.6 on 2022-09-30 11:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='SectionImage', verbose_name='Section3 Image')),
            ],
            options={
                'verbose_name_plural': 'Section Image',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category Title')),
            ],
        ),
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sales')),
            ],
            options={
                'verbose_name_plural': 'Total Sales',
            },
        ),
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(blank=True, max_length=150, null=True, verbose_name='Section3 Heading')),
                ('section_sub_heading', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section3 Sub Heading')),
                ('section_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.sectionimage')),
            ],
            options={
                'verbose_name_plural': 'Section 3',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Product Heading')),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Discription')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('product_url', models.URLField(blank=True, null=True)),
                ('cat_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.title')),
                ('total_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.totalsales')),
            ],
        ),
    ]
